services:

  db-user-service:
    image: postgres
    container_name: db-user-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=user_service_password
      - POSTGRES_USER=user_service_user
      - POSTGRES_DB=user-service
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  redis:
      image: redis/redis-stack:latest
      restart: always
      ports:
        - 6379:6379
        - 8001:8001
      volumes:
        - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5050:80'
    depends_on:
      - db-user-service
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  

volumes:
  pgdata:
  pgadmin_data:
  redis_data: